### ISSUE TITLE
PA REVIEW: User Authentication

### ISSUE THREAD

**Issue by walterhwan** [walterhwan/remember_the_bacon#2]
- [x] User can login/logout/signup
- [x] Guest Demo login
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by AAlfarho** [comment]
Great job on the User Auth a couple of details.
- [x] When trying to `log in` with incorrect credentials, we mention something about resetting the password, as we don't have that functionality, let's remove that from the error message.
- [x] When `signing up` a user with missing information, the message `Sorry, that wasn't a valid user information` does not shed light into what went wrong, let's have detailed information of what went wrong. Rails already provide us with what exactly went wrong.
- [x] User auth errors are not cleared when switching between login & signup. Steps to reproduce:
   + Login with invalid credentials.
   + An error will show up.
   + Clicking on `Sign up for free` loads a new component and displays some errors even if we haven't yet created a user.
- [x] (Optional) What do you think about also adding the demo login button on the `sign up` component?


Great job handling non-existing routes (`/#/non-existing-route`) as well as redirecting to log in when a user signs out.

Assign this issue back to once you address the feedback.

**Comment by AAlfarho** [comment]
Great job!

Our landing page is the first impression users will get from our site, kudos on finishing this MVP.

MVP is now complete
